#!/usr/bin/env bash
# This script generates a 4096-bit RSA SSH key pair
# Private key name: school
# Passphrase: betty
# Format: OpenSSH (required by checker)

ssh-keygen -t rsa -b 4096 -f school -N "betty" -o