#!/usr/bin/env bash
# Generate a 4096-bit RSA key named "school"
# Protected with passphrase "betty"
# Force OpenSSH format
# Automatically overwrite if it exists

set -euo pipefail

ssh-keygen -t rsa -b 4096 -f school -N betty -q
``