#!/usr/bin/env bash
# Configure nginx to add custom header

apt-get update -y
apt-get install -y nginx

sed -i '/add_header X-Served-By/d' /etc/nginx/sites-available/default

sed -i '/server_name _;/a \    add_header X-Served-By $hostname always;' \
/etc/nginx/sites-available/default

service nginx restart
