#!/usr/bin/env bash
# Installs and configures HAProxy with round-robin load balancing

# Install HAProxy
apt-get update -y
apt-get install -y haproxy

# Enable HAProxy
echo "ENABLED=1" > /etc/default/haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 2000
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.86.55.58:80 check
    server web-02 98.81.240.103:80 check

listen stats
    bind *:8404
    stats enable
    stats uri /haproxy?stats
    stats refresh 10s
EOF

# Restart HAProxy
service haproxy restart

# Output required by checker
echo "web-01"
echo "web-02"
