#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 and starts the service

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart