#!/usr/bin/env bash
# Installs and configures Nginx to serve a page containing 'Holberton School' on port 80.
set -e

# Update package list
apt-get update -y

# Install nginx
apt-get install -y nginx

# Ensure nginx is enabled and running
service nginx start

# Overwrite default page
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Restart nginx without systemctl
service nginx restart