#!/usr/bin/env bash
# Installs and configures Nginx with a permanent redirection.
set -e

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

if ! grep -q "^\s*rewrite \^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default; then
  sed -i '/listen 80 default_server;/a\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
fi

service nginx restart