#!/usr/bin/env bash
# Installs and configures Nginx with a permanent redirection.
set -e

apt update -y
apt install -y nginx

echo "Holberton School" > /var/www/html/index.html

cat <<'EOF' > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

service nginx restart