#!/usr/bin/env bash
# Installs and configures Nginx with redirection and a custom 404 page.

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

echo "$config" > /etc/nginx/sites-available/default
sudo service nginx restart
